name: social_stream_next
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1  
  flutter_svg: ^2.0.9
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  firebase_analytics: ^11.3.0
  flutter_riverpod: ^2.6.1
  image_picker: ^1.0.7
  http: ^1.1.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.4.4
  app_links: ^6.3.0
  google_generative_ai: ^0.4.0
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  flutter_markdown: ^0.7.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/logo/
